In [3]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import StandardScaler

In [4]:
Data = pd.read_csv('practice.txt', sep = '\t', index_col = 0)

In [5]:
Data

Mate  Ciencias  Espa  Hist  EdF
Estudiante                                 
Lucia        7.0       6.5   9.2   8.6  8.0
Pedro        7.5       9.4   7.3   7.0  7.0
Ines         7.6       9.2   8.0   8.0  7.5
Luis         5.0       6.5   6.5   7.0  9.0
Andres       6.0       6.0   7.8   8.9  7.3
Ana          7.8       9.6   7.7   8.0  6.5
Carlos       6.3       6.4   8.2   9.0  7.2
Jose         7.9       9.7   7.5   8.0  6.0
Sonia        6.0       6.0   6.5   5.5  8.7
Maria        6.8       7.2   8.7   9.0  7.0

In [6]:
#Estandarizar
Data_stan = StandardScaler().fit_transform(Data)
Data_stan

array([[ 0.23263076, -0.7529862 ,  1.78848525,  0.65792263,  0.65858084],
       [ 0.78651352,  1.14584856, -0.53899555, -0.84590053, -0.47690337],
       [ 0.89729007,  1.01489444,  0.31849737,  0.09398895,  0.09083874],
       [-1.98290027, -0.7529862 , -1.51898747, -0.84590053,  1.79406505],
       [-0.87513476, -1.0803715 ,  0.07349939,  0.93988948, -0.13625811],
       [ 1.11884317,  1.27680268, -0.0489996 ,  0.09398895, -1.04464547],
       [-0.5428051 , -0.81846326,  0.56349535,  1.03387842, -0.24980653],
       [ 1.22961972,  1.34227974, -0.29399757,  0.09398895, -1.61238758],
       [-0.87513476, -1.0803715 , -1.51898747, -2.25573474,  1.45341979],
       [ 0.01107766, -0.29464677,  1.1759903 ,  1.03387842, -0.47690337]])

In [7]:
Corr = np.corrcoef(Data_stan.T)
Corr

array([[ 1.        ,  0.85407878,  0.38457424,  0.20719425, -0.78716269],
       [ 0.85407878,  1.        , -0.02005218, -0.02153942, -0.68772056],
       [ 0.38457424, -0.02005218,  1.        ,  0.82091619, -0.36554342],
       [ 0.20719425, -0.02153942,  0.82091619,  1.        , -0.50800132],
       [-0.78716269, -0.68772056, -0.36554342, -0.50800132,  1.        ]])

In [8]:
from sklearn.decomposition import PCA

In [9]:
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(Data_stan)

In [10]:
principalComponents

array([[-0.32306263,  1.7725245 ],
       [-0.66544057, -1.63870215],
       [-1.00254705, -0.51569247],
       [ 3.17209481, -0.26278201],
       [ 0.48886797,  1.3654021 ],
       [-1.70863322, -1.02170044],
       [-0.06758577,  1.46233642],
       [-2.01185516, -1.27586457],
       [ 3.04203029, -1.25488069],
       [-0.92386867,  1.3693593 ]])

In [11]:
#varianza de Componente 1 es primer valor propio
principalComponents[:,0].var()

2.89324967341795

In [12]:
principalComponents[:,1].var()

1.6286504249773173

In [13]:
from numpy import linalg as LA

In [14]:
w, v = LA.eig(Corr)

In [15]:
w

array([2.89324967, 1.62865042, 0.34659605, 0.00889139, 0.12261246])

In [35]:
circ=np.corrcoef(principalComponents[:,0], Data_stan[:,0])

In [46]:
principalComponents[:,0]

array([-0.32306263, -0.66544057, -1.00254705,  3.17209481,  0.48886797,
       -1.70863322, -0.06758577, -2.01185516,  3.04203029, -0.92386867])

In [34]:
Data_stan[:,0]

array([ 0.23263076,  0.78651352,  0.89729007, -1.98290027, -0.87513476,
        1.11884317, -0.5428051 ,  1.22961972, -0.87513476,  0.01107766])

In [36]:
for 

array([[ 1.        , -0.89579797],
       [-0.89579797,  1.        ]])

In [43]:
Data_stan[0,:].size

5

In [66]:
circ = np.empty((5,2),dtype=object)    
for i in range(0,5) :
    for j in range(0,2) :
        circ[i,j]=np.corrcoef(principalComponents[:,j], Data_stan[:,i])[0,1]  

In [67]:
circ

array([[-0.8957979732823264, -0.34520356427322774],
       [-0.7227976078832452, -0.6483945910563976],
       [-0.6108931347179855, 0.7173205982157781],
       [-0.599922708112768, 0.7484700733922538],
       [0.9139264766733469, 0.11963731479238988]], dtype=object)

In [68]:
print(pca.explained_variance_ratio_) 

[0.57864993 0.32573008]


In [70]:
print(pca.components_) 

[[-0.52664397 -0.42493622 -0.35914704 -0.35269747  0.53730181]
 [-0.2704963  -0.50807221  0.56208159  0.58648985  0.09374599]]


In [72]:
print(pca.explained_variance_) 

[3.21472186 1.80961158]
